:hivemq-github: https://github.com/hivemq
:hivemq-website: http://www.hivemq.com
:hivemq-community-forum: https://community.hivemq.com/
:hivemq-extensions-docu: http://www.hivemq.com/docs/latest/extensions/
:hivemq-marketplace: http://www.hivemq.com/extensions/

= HiveMQ Extension SDK

image:https://maven-badges.herokuapp.com/maven-central/com.hivemq/hivemq-extension-sdk/badge.svg["Maven Central",link="https://maven-badges.herokuapp.com/maven-central/com.hivemq/hivemq-extension-sdk"]
image:https://javadoc.io/badge2/com.hivemq/hivemq-extension-sdk/javadoc.svg["javadoc", link=https://javadoc.io/doc/com.hivemq/hivemq-extension-sdk]

The enterprise MQTT broker HiveMQ offers this free, open source extension SDK.
The HiveMQ extension framework provides an open API that allows developers to create custom extensions that suit their specific infrastructures.
Use our extension framework to extend HiveMQ with custom business logic or to integrate virtually any system into HiveMQ.

The HiveMQ extension framework can be used to add many different types of functionality:

* Write messages to a database,
* integrate other services,
* collect statistics,
* add fine-grained security,
* and much more.

Resources:

* Web Site: {hivemq-website}
* Documentation: {hivemq-extensions-docu}
* Community Forum: {hivemq-community-forum}
* Contribution Guidelines: link:CONTRIBUTING.adoc[Contributing.adoc]
* License: The source files in this repository are made available under the link:LICENSE[Apache License Version 2.0].

== Using the SDK

The HiveMQ extension SDK is available in Maven central, so no special configuration is needed.
To use the SDK, add the following dependency to your Maven project:

[source,xml]
----
<dependency>
    <groupId>com.hivemq</groupId>
    <artifactId>hivemq-extension-sdk</artifactId>
    <version>4.4.2</version>
</dependency>
----

== Extension Development Documentation

Extension development for HiveMQ is as easy as writing a Java main method once you grasp the core concepts.

Please visit the extensive {hivemq-extensions-docu}[HiveMQ extension developer documentation].
It covers the core concepts and shows how to set up your development environment.

== Example Extensions

You can find many example extensions by browsing the {hivemq-github}[HiveMQ GitHub space].

Check out the {hivemq-marketplace}[HiveMQ Marketplace] for officially supported extensions.

== Need help ?

If you need help with custom HiveMQ extensions please contact support@hivemq.com.

== Contributing

If you want to contribute to the HiveMQ Extension SDK, see the link:CONTRIBUTING.md[contribution guidelines].

== License

The HiveMQ Extension SDK is licensed under the `APACHE LICENSE, VERSION 2.0`.
A copy of the license can be found link:LICENSE[here].
