[versions]
dropwizard-metrics = "4.2.19"
slf4j = "2.0.7"

[libraries]
dropwizard-metrics = { module = "io.dropwizard.metrics:metrics-core", version.ref = "dropwizard-metrics" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
